/**
 * Example demonstrating code execution with UserProxyAgent
 * This shows how to automatically execute code generated by the assistant
 */
import { AssistantAgent, UserProxyAgent, LocalCodeExecutor, HumanInputMode } from '../index';
import * as dotenv from 'dotenv';

dotenv.config();

async function main() {
  if (!process.env.OPENAI_API_KEY) {
    console.error('Please set OPENAI_API_KEY in your .env file');
    process.exit(1);
  }

  // Create code executor
  const codeExecutor = new LocalCodeExecutor();

  // Create assistant that can write code
  const assistant = new AssistantAgent({
    name: 'assistant',
    apiKey: process.env.OPENAI_API_KEY!,
    systemMessage: `You are a helpful coding assistant. When asked to solve problems, write code and present it in markdown code blocks.
    
For example:
\`\`\`javascript
console.log("Hello, World!");
\`\`\`

Always use console.log() to display results in JavaScript.`,
    model: 'gpt-3.5-turbo',
    temperature: 0
  });

  // Create user proxy with code execution enabled
  const userProxy = new UserProxyAgent({
    name: 'user_proxy',
    humanInputMode: HumanInputMode.NEVER,
    codeExecutor: codeExecutor,
    autoExecuteCode: true
  });

  console.log('===== Code Execution Example =====\n');
  console.log('Task: Calculate the sum of numbers from 1 to 100\n');

  // Initiate chat
  const history = await userProxy.initiateChat(
    assistant,
    'Write JavaScript code to calculate the sum of numbers from 1 to 100 and print the result.',
    3
  );

  console.log('\n---\n');
  console.log('Task: Generate Fibonacci sequence\n');

  // Clear history
  assistant.clearHistory();
  userProxy.clearHistory();

  await userProxy.initiateChat(
    assistant,
    'Write JavaScript code to generate the first 10 numbers in the Fibonacci sequence and print them.',
    3
  );

  console.log('\n---\n');
  console.log('Task: Sort an array\n');

  // Clear history
  assistant.clearHistory();
  userProxy.clearHistory();

  await userProxy.initiateChat(
    assistant,
    'Write JavaScript code to sort this array [64, 34, 25, 12, 22, 11, 90] in ascending order and print the result.',
    3
  );

  // Cleanup
  await codeExecutor.cleanup();
  userProxy.close();
}

main().catch(console.error);
